/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.micks.pmadmin;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import com.micks.pmlib1.LibraryOne;
import com.micks.pmlib2.LibraryTwo;

@Slf4j
@RestController
@SpringBootApplication(scanBasePackages = {"com.micks"})
public class MainWebApp implements CommandLineRunner {

    private final LibraryOne libraryOne;
    private final LibraryTwo libraryTwo;

    public MainWebApp(LibraryOne libraryOne, LibraryTwo libraryTwo) {
        this.libraryOne = libraryOne;
        this.libraryTwo = libraryTwo;
    }

    /**
     * Entry point for the Spring-boot container
     *
     * @param args command line args
     */
    public static void main(String[] args) {

        SpringApplication.run(MainWebApp.class, args);
    }

    @GetMapping("/")
    public String home() {

        String str = "Hello kitty from Mick on sb-web-app #1";
        log.info("Controller returning message = {}", str);

        return str;
    }

    @Override
    public void run(String... args) throws Exception {

        libraryOne.someLibraryOneMethod();
        libraryTwo.someLibraryTwoMethod();

    }
}
