/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.micks.pmadmin;


import org.junit.jupiter.api.Test;

public class AppTest {

    @Test
    public void testAppHasAGreeting() {

    }
}
