/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.micks.pmlib1;


import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContext;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import static org.springframework.test.util.AssertionErrors.assertTrue;

@AutoConfigureWebTestClient(timeout = "36000")
@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = {LibraryOne.class})
@SpringBootTest
public class LibraryOneTest {

    @Autowired
    private ApplicationContext context;

    @Autowired
    LibraryOne libraryOne;

    @Test
    public void testSomeLibraryOneMethod() {
        assertTrue("someLibraryOneMethod should return 'true'",
                libraryOne.someLibraryOneMethod());
    }

}
