/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.micks.pmlib1;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

@Slf4j
@Service
public class LibraryOne {

    public boolean someLibraryOneMethod() {

        LombokOneTest lombokOneTest = new LombokOneTest();

        log.info("Just ran someLibraryOneMethod()...");

        return true;
    }

}
