/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.micks.pmlib;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

@Slf4j
@Service
public class Library {

    public boolean someLibraryMethod() {

        LombokTest lombokTest = new LombokTest();

        log.info("Just ran someLibraryMethod()...");

        return true;
    }

}
