/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.micks.pmlib;


import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

import static org.springframework.test.util.AssertionErrors.assertTrue;

public class LibraryTest {

    @Autowired
    Library library;

    @Test
    public void testSomeLibraryMethod() {
        assertTrue("someLibraryMethod should return 'true'",
                library.someLibraryMethod());
    }

}
